package com.github.maxopoly.WPCommon.model.permission;

public enum Permission {

	ALT_LOOKUP, STANDING_LOOKUP, CHEST_LOOKUP, CHEST_POST, OWN_LOCATION_POST, RADAR_LOCATION_POST, SNITCH_LOCATION_POST,

	RADAR_LOCATION_READ, SNITCH_LOCATION_READ, MAP_SYNC, TACTICAL_WAYPOINTS, SECRET_WAYPOINTS, AUTH;

}
